/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.Clock;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToolBar1 = new javax.swing.JToolBar();
        btn_dangXuat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_quanLySV = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_quanLyDiem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnu_dangNhap = new javax.swing.JMenuItem();
        mnu_dangXuat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnu_quanLySV = new javax.swing.JMenuItem();
        mnu_quanLyDiem = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home.png"))); // NOI18N
        btn_dangXuat.setText("Đăng Xuất");
        btn_dangXuat.setFocusable(false);
        btn_dangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangXuat);
        jToolBar1.add(jSeparator1);

        btn_quanLySV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        btn_quanLySV.setText("Quản Lý Sinh Viên");
        btn_quanLySV.setFocusable(false);
        btn_quanLySV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLySV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLySV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLySVActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLySV);
        jToolBar1.add(jSeparator2);

        btn_quanLyDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/To do list.png"))); // NOI18N
        btn_quanLyDiem.setText("Quản Lý Điểm");
        btn_quanLyDiem.setFocusable(false);
        btn_quanLyDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyDiem);

        jMenu1.setText("Hệ Thống");

        mnu_dangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login.png"))); // NOI18N
        mnu_dangNhap.setText("Đăng Nhâp");
        mnu_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_dangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_dangNhap);

        mnu_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home.png"))); // NOI18N
        mnu_dangXuat.setText("Đăng Xuất");
        mnu_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_dangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_dangXuat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        mnu_quanLySV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        mnu_quanLySV.setText("Quản Lý Sinh Viên");
        mnu_quanLySV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_quanLySVActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_quanLySV);

        mnu_quanLyDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/To do list.png"))); // NOI18N
        mnu_quanLyDiem.setText("Quản Lý Điểm");
        mnu_quanLyDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_quanLyDiemActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_quanLyDiem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_quanLySVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_quanLySVActionPerformed
        new QuanLySinhVien(null, true).show();
    }//GEN-LAST:event_mnu_quanLySVActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btn_quanLySVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLySVActionPerformed
     new QuanLySinhVien(null, true).show();
    }//GEN-LAST:event_btn_quanLySVActionPerformed

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        int kt = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không", "thoát", JOptionPane.YES_NO_OPTION);
        if (kt == 0) {
            System.exit(0);
        } else {
            return;
        }


    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_quanLyDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyDiemActionPerformed
       new QuanLyDiem(null, true).show();
    }//GEN-LAST:event_btn_quanLyDiemActionPerformed

    private void mnu_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_dangNhapActionPerformed
       new DangNhap(null, true).show();
    }//GEN-LAST:event_mnu_dangNhapActionPerformed

    private void mnu_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_dangXuatActionPerformed
        int kt = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không", "thoát", JOptionPane.YES_NO_OPTION);
        if (kt == 0) {
            System.exit(0);
        } else {
            return;
        }
    }//GEN-LAST:event_mnu_dangXuatActionPerformed

    private void mnu_quanLyDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_quanLyDiemActionPerformed
          new QuanLyDiem(null, true).show();
    }//GEN-LAST:event_mnu_quanLyDiemActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_quanLyDiem;
    private javax.swing.JButton btn_quanLySV;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnu_dangNhap;
    private javax.swing.JMenuItem mnu_dangXuat;
    private javax.swing.JMenuItem mnu_quanLyDiem;
    private javax.swing.JMenuItem mnu_quanLySV;
    // End of variables declaration//GEN-END:variables
}
